$schema: 'https://moonrepo.dev/schemas/template.json'

# Name of the template in a human readable format.
title: 'Title'

# Description of what the template is for, it does, and anything else.
description: 'Description of the template.'
